import { tool, type GeneratedFile } from 'ai';
import { z } from 'zod';
import { generateText } from 'ai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import type { ToolDetails } from '../types';
import { toOpenAgenticTool } from './utils';
import { uploadImageToS3, generateImageFileName } from '../utils/s3';

interface GeminiImageFile extends GeneratedFile {
  base64Data: string;
  name: string;
}

// Supported Gemini models with image generation capabilities
const SUPPORTED_MODELS = [
  'gemini-2.0-flash-preview-image-generation',
  // 'gemini-2.0-flash-thinking-exp',
] as const;

// Supported image styles for Gemini
const IMAGE_STYLES = [
  'photorealistic',
  'artistic',
  'cartoon',
  'sketch',
  'digital-art',
  'oil-painting',
  'watercolor',
  'minimalist',
  'abstract',
  'cinematic',
] as const;

const rawGeminiImageTool = tool({
  description: 'Generate high-quality images using Google Gemini models with automatic S3 upload and storage',
  parameters: z.object({
    prompt: z.string()
      .min(1)
      .max(4000)
      .describe('The text prompt to generate an image from (required, max 4000 characters)'),
    
    model: z.string()
      .optional()
      .default('gemini-2.0-flash-preview-image-generation')
      .describe('The Gemini model to use (gemini-2.0-flash-preview-image-generation)'),
    
    style: z.enum(IMAGE_STYLES)
      .optional()
      .describe('The style of the image (photorealistic, artistic, cartoon, sketch, digital-art, oil-painting, watercolor, minimalist, abstract, cinematic)'),
    
    aspectRatio: z.enum(['1:1', '16:9', '9:16', '4:3', '3:4'])
      .optional()
      .default('1:1')
      .describe('The aspect ratio of the image (default: 1:1)'),
    
    quality: z.enum(['standard', 'high'])
      .optional()
      .default('standard')
      .describe('The quality of the image generation (standard, high)'),
  }),
  
  execute: async ({ 
    prompt,
    model = 'gemini-2.0-flash-exp',
    style,
    aspectRatio = '1:1',
    quality = 'standard'
  }) => {
    // Validate API key
    const apiKey = process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      throw new Error('GOOGLE_API_KEY environment variable is required');
    }

    // Validate prompt
    if (!prompt || prompt.trim().length === 0) {
      throw new Error('Prompt cannot be empty');
    }

    if (prompt.length > 4000) {
      throw new Error('Prompt exceeds maximum length of 4000 characters');
    }

    // Validate model
    if (!SUPPORTED_MODELS.includes(model as any)) {
      throw new Error(`Model "${model}" not in supported list. Supported models: ${SUPPORTED_MODELS.join(', ')}`);
    }

    // Start logging
    console.log('🎨 Gemini Image Generation Tool - Generation started:', {
      timestamp: new Date().toISOString(),
      prompt: prompt.substring(0, 100) + (prompt.length > 100 ? '...' : ''),
      promptLength: prompt.length,
      model,
      style,
      aspectRatio,
      quality,
    });

    try {
      // Initialize Google AI client
      const google = createGoogleGenerativeAI({
        apiKey,
      });

      // Enhance prompt with style and aspect ratio guidance
      let enhancedPrompt = prompt.trim();
      if (style) {
        enhancedPrompt = `Create a ${style} style image: ${enhancedPrompt}`;
      }
      if (aspectRatio !== '1:1') {
        enhancedPrompt += ` (aspect ratio: ${aspectRatio})`;
      }
      if (quality === 'high') {
        enhancedPrompt += ' (high quality, detailed)';
      }

      console.log('🤖 Calling Gemini with enhanced prompt for image generation...');

      // Generate image using Gemini with image output modality
      const result = await generateText({
        model: google(model),
        prompt: enhancedPrompt,
        providerOptions: {
          google: { 
            responseModalities: ['TEXT', 'IMAGE'],
          },
        },
      });

      // Check if we have generated files
      if (!result.files || result.files.length === 0) {
        throw new Error('No files were generated by Gemini. The model may not have produced an image.');
      }

      // Find the first image file
      const imageFile = result.files.find(file => 
        file.mimeType && file.mimeType.startsWith('image/')
      ) as GeminiImageFile;

      if (!imageFile) {
        throw new Error('No image file found in Gemini response. Only non-image files were generated.');
      }

      if (!imageFile.base64Data) {
        throw new Error('No base64 data found in generated image file');
      }

      // Convert response to buffer
      const imageBuffer = Buffer.from(imageFile.base64Data, 'base64');

      if (imageBuffer.length === 0) {
        throw new Error('Downloaded image buffer is empty');
      }

      // Determine file extension from MIME type
      const extension = imageFile.mimeType === 'image/jpeg' ? 'jpg' : 
                       imageFile.mimeType === 'image/png' ? 'png' : 
                       imageFile.mimeType === 'image/webp' ? 'webp' : 
                       'jpg'; // Default fallback

      // Generate filename for S3 upload
      const fileName = generateImageFileName(prompt, extension);

      // Upload to S3
      console.log('📤 Uploading generated image to S3...');
      const imageUrl = await uploadImageToS3(
        imageBuffer,
        fileName,
        imageFile.mimeType || 'image/jpeg',
        `Gemini ${model} generated image: ${prompt.substring(0, 100)}`
      );

      // Log completion
      console.log('✅ Gemini Image Generation Tool - Generation completed:', {
        model,
        style,
        aspectRatio,
        quality,
        imageUrl,
        fileName,
        imageSize: imageBuffer.length,
        mimeType: imageFile.mimeType,
        originalName: imageFile.name,
      });

      // Return structured result
      return {
        success: true,
        imageUrl,
        fileName,
        model,
        style,
        aspectRatio,
        quality,
        originalPrompt: prompt.trim(),
        enhancedPrompt,
        generatedText: result.text || null,
        metadata: {
          generatedAt: new Date().toISOString(),
          promptLength: prompt.length,
          fileSize: imageBuffer.length,
          mimeType: imageFile.mimeType,
          originalFileName: imageFile.name,
          uploadedToS3: true,
        },
      };

    } catch (error) {
      console.error('❌ Gemini Image Generation Tool - Generation failed:', {
        model,
        style,
        aspectRatio,
        quality,
        promptLength: prompt.length,
        error: error instanceof Error ? error.message : String(error),
      });

      // Handle specific error types
      if (error instanceof Error) {
        // Rate limiting error
        if (error.message.includes('rate limit') || error.message.includes('429') || 
            error.message.includes('quota') || error.message.includes('limit exceeded')) {
          throw new Error('Google API rate limit or quota exceeded. Please try again later.');
        }
        
        // Authentication error
        if (error.message.includes('401') || error.message.includes('authentication') || 
            error.message.includes('unauthorized')) {
          throw new Error('Google API authentication failed. Please check your GOOGLE_API_KEY environment variable.');
        }
        
        // Invalid model error
        if (error.message.includes('model') && error.message.includes('not found')) {
          throw new Error(`Invalid model "${model}". Please use a supported Gemini model with image generation capabilities.`);
        }
        
        // Content policy violation
        if (error.message.includes('content policy') || error.message.includes('safety') || 
            error.message.includes('blocked') || error.message.includes('filtered')) {
          throw new Error('Image generation request violates Google content policy or safety filters. Please modify your prompt.');
        }
        
        // Prompt too long error
        if (error.message.includes('prompt') && error.message.includes('too long')) {
          throw new Error('Prompt is too long. Please reduce the prompt length and try again.');
        }
        
        // Image generation specific errors
        if (error.message.includes('No files were generated') || error.message.includes('No image file found')) {
          throw new Error('Gemini did not generate an image. Try rephrasing your prompt or adding more descriptive details.');
        }
        
        // Download errors
        if (error.message.includes('download') || error.message.includes('fetch') || 
            error.message.includes('download URL')) {
          throw new Error('Failed to download generated image from Gemini. Please try again.');
        }
        
        // Network errors
        if (error.message.includes('network') || error.message.includes('timeout') || 
            error.message.includes('ECONNREFUSED') || error.message.includes('ETIMEDOUT')) {
          throw new Error('Network error connecting to Google API. Please check your internet connection.');
        }
        
        // S3 upload errors
        if (error.message.includes('S3') || error.message.includes('upload')) {
          throw new Error('Failed to upload generated image to S3. Please check your S3 configuration.');
        }
        
        // Buffer processing errors
        if (error.message.includes('buffer') || error.message.includes('empty')) {
          throw new Error('Failed to process generated image data. Please try again.');
        }
        
        // Service availability errors
        if (error.message.includes('502') || error.message.includes('503') || error.message.includes('504') ||
            error.message.includes('service unavailable') || error.message.includes('server error')) {
          throw new Error('Google Gemini service temporarily unavailable. Please try again later.');
        }
        
        // Image modality errors
        if (error.message.includes('modality') || error.message.includes('responseModalities')) {
          throw new Error('Image generation modality not supported by this Gemini model. Please try a different model.');
        }
      }

      // Generic error fallback
      throw new Error(`Gemini image generation failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  },
});

const toolDetails: ToolDetails = {
  toolId: 'gemini_image_generator',
  name: 'Gemini Image Generator',
  useCases: [
    'Generate photorealistic images from text descriptions using Gemini',
    'Create artistic illustrations and digital art with AI',
    'Generate concept art for creative projects',
    'Create custom artwork for presentations and documents',
    'Generate images in various artistic styles (cartoon, sketch, oil-painting)',
    'Create marketing visuals and social media content',
    'Generate educational and explanatory images',
    'Create abstract and minimalist artwork',
    'Generate cinematic and dramatic imagery',
    'Create watercolor and traditional art style images',
    'Generate images with specific aspect ratios for different use cases',
    'Create high-quality detailed images for professional use',
  ],
  logo: 'https://www.openagentic.org/tools/gemini.svg',
};

export const geminiImageTool = toOpenAgenticTool(rawGeminiImageTool, toolDetails);